version: '3'

services:
  runtimes-api:
    build: .
    command: npm start
    volumes:
      - ./code:/usr/app/code:rw
    ports:
      - "3000:3000"
  runtimes-executor:
    container_name: runtimes-executor
    stop_signal: SIGINT
    image: openruntimes/executor:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:rw
      - ./code:/code:rw
    environment:
      - OPR_EXECUTOR_CONNECTION_STORAGE=local://localhost
      - OPR_EXECUTOR_SECRET=my-secret